name = "rikuhub"
main = "packages/worker/src/index.ts"
compatibility_date = "2025-03-01"
workers_dev = true

[assets]
directory = "./packages/web/dist"
binding = "ASSETS"

[vars]
AGGREGATE_TTL_SECONDS = "3600"
MAX_LOG_ENTRIES = "200"

[[kv_namespaces]]
binding = "CACHE_KV"

[[d1_databases]]
binding = "DB"
database_name = "riku-hub-db"

[triggers]
crons = ["0 * * * *"]
